openapi: '3.0.3'
info:
  title: Team.In-site
  version: '0.1.0'

servers:
  - url: http://localhost:3000/api/v1

tags:
  - name: Auth
  - name: User

paths:
  /health:
    servers:
      - url: http://localhost:3000/
    get:
      responses:
        '200':
          description: OK

  /auth/register:
    post:
      tags: [Auth]
      summary: 회원 가입
      description: '회원가입 시에 사용되는 엔드포인트입니다.'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/AuthRegisterRequest' }
      responses:
        '201':
          description: '신규 계정이 생성되고 인증 토큰이 쿠키로 발급됩니다.'
          headers:
            Set-Cookie:
              description: '`token=<JWT>` 형태의 httpOnly 쿠키'
              schema: { type: string }
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AuthResponse' }
        '400':
          description: '잘못된 요청(아이디/비밀번호/이메일/선호 정보 검증 실패)'
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '409':
          description: '아이디 혹은 이메일 중복'
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '500':
          description: '서버 내부 오류'

  /auth/login:
    post:
      tags: [Auth]
      summary: 로그인
      description: '이메일/비밀번호를 검증하고 인증 토큰을 발급합니다.'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/AuthLoginRequest' }
      responses:
        '200':
          description: '로그인 성공. 인증 토큰이 쿠키로 발급됩니다.'
          headers:
            Set-Cookie:
              description: '`token=<JWT>` 형태의 httpOnly 쿠키'
              schema: { type: string }
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AuthResponse' }
        '400':
          description: '이메일/비밀번호 누락 혹은 형식 오류'
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '401':
          description: '이메일 혹은 비밀번호 불일치'
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '500':
          description: '서버 내부 오류'

  /user/check-id/{user_id}:
    get:
      tags: [User]
      summary: 아이디 중복 여부 확인
      description: '가입 전에 특정 아이디가 사용 가능한지 확인합니다.'
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
            minLength: 3
            maxLength: 50
            pattern: '^[a-zA-Z0-9_-]+$'
          description: '중복 여부를 확인할 아이디'
      responses:
        '200':
          description: '아이디 사용 가능 여부'
          content:
            application/json:
              schema: { $ref: '#/components/schemas/UserCheckIdResponse' }
        '400':
          description: '아이디가 요구 조건을 만족하지 않음'
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '500':
          description: '서버 내부 오류'

components:
  schemas:
    # ==== AUTH ====
    AuthRegisterRequest:
      type: object
      required: [user_id, email, password, language, level, purpose]
      properties:
        user_id:
          type: string
          minLength: 3
          maxLength: 50
          pattern: '^[a-zA-Z0-9_-]+$'
          description: '3~50자의 영문/숫자/언더스코어/하이픈(앞뒤 공백은 자동 제거)'
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
          maxLength: 128
          format: password
        language:
          type: string
          enum: [py, js, cpp, other]
          description: '선호 프로그래밍 언어'
        level:
          type: integer
          minimum: 1
          maximum: 4
          description: '숙련도(1~4)'
        purpose:
          type: string
          enum: [prob, proj, learn]
          description: '가입 목적'

    AuthLoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
          format: password

    AuthResponse:
      type: object
      required: [user_id, email]
      properties:
        user_id:
          type: string
        email:
          type: string
          format: email

    ErrorResponse:
      type: object
      required: [name, message]
      properties:
        name:
          type: string
          description: '서버에서 정의한 에러 식별자'
        message:
          type: string
          description: '사용자에게 전달되는 에러 메시지'
        stack:
          type: string
          description: '개발 환경에서만 노출되는 stack trace'

    # ==== USER ====
    UserCheckIdResponse:
      type: object
      required: [available]
      properties:
        available:
          type: boolean
          description: 'true이면 아직 사용되지 않은 아이디'
